use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let assets = PathBuf::from(&manifest_dir).join("assets").join("sprites");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("builtin_sprites.rs");

    println!("cargo:rerun-if-changed=assets/sprites");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&assets) {
        for entry in rd.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let id = match path.file_stem().and_then(|s| s.to_str()) {
                Some(s) if !s.is_empty() => s.to_string(),
                _ => continue,
            };
            let raw = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
            entries.push((id, raw));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// generated by build.rs — do not edit\n");
    out.push_str("pub static BUILTIN_SPRITES: &[(&str, &str)] = &[\n");
    for (id, raw) in &entries {
        out.push_str(&format!("    ({:?}, {:?}),\n", id, raw));
    }
    out.push_str("];\n");
    fs::write(&out_path, out).expect("write builtin_sprites.rs");

    // Slint UI for the ytmtui-gui binary. The .slint file rerun is handled
    // by slint-build itself; we only need to nudge cargo when the file
    // moves on disk.
    let slint_path = PathBuf::from(&manifest_dir).join("ui").join("main.slint");
    println!("cargo:rerun-if-changed={}", slint_path.display());
    slint_build::compile(&slint_path).expect("compile Slint UI");
}
